module.exports = [
  {
    title: "Frozen",
    poster: "https://posters.movieposterdb.com/13_09/2013/2294629/l_2294629_7342c9bf.jpg",
    year: "2013",
    director: "Chris Buck",
    genre: "Kids",
  },
  {
    title: "Lion King",
    poster: "https://m.media-amazon.com/images/I/612YWU3cO1L._AC_SL1000_.jpg",
    year: "1994",
    director: "George Scribner",
    genre: "Musical Drama",
  },
  {
    title: "Zootopia",
    poster: "https://m.media-amazon.com/images/I/71hWkxTBHRL.jpg",
    year: "2016",
    director: "Byron howard",
    genre: "Action/Comedy",
  },
  {
    title: "Pretty Woman",
    poster: "https://images-na.ssl-images-amazon.com/images/I/61ETzNx3+sL._AC_UL600_SR600,600_.jpg",
    year: "1994",
    director: "Garry Marshall",
    genre: "Romance",
  },
  {
    title: "True Lies",
    poster: "https://m.media-amazon.com/images/M/MV5BYzg5YmUyNGMtMThiNS00MjA2LTgwZDctNDlhM2RkZDNmZmRkXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg",
    year: "1994",
    director: "James Cameron",
    genre: "Action",
  },
  {
    title: "The Sixth Sense",
    poster: "https://i.ebayimg.com/images/g/~rIAAOSwMJJg5rJL/s-l1600.jpg",
    year: "1999",
    director: "M. Night Shyamalan",
    genre: "Thriller",
  },
  {
    title: "Spider-Man: Across the Spider-Verse",
    poster: "https://m.media-amazon.com/images/M/MV5BMzI0NmVkMjEtYmY4MS00ZDMxLTlkZmEtMzU4MDQxYTMzMjU2XkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_FMjpg_UX1000_.jpg",
    year: "2023",
    director: "Joaquim Dos Santos",
    genre: "Action",
  },
  {
    title: "Whiplash",
    poster: "https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
    year: "2014",
    director: "Damien Chazelle",
    genre: "Drama",
  },
  {
    title: "Interstellar",
    poster: "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
    year: "2014",
    director: "Christopher Nolan",
    genre: "Science Fiction",
  },
  {
    title: "The Shawshank Redemption",
    poster: "https://m.media-amazon.com/images/M/MV5BMTQ1ODM2MjY3OV5BMl5BanBnXkFtZTgwMTU2MjEyMDE@._V1_.jpg",
    year: "1994",
    director: "Frank Darabont",
    genre: "Drama",
  },
  {
    title: "The Godfather",
    poster: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg",
    year: "1972",
    director: "Francis Ford Coppola",
    genre: "Crime",
  },
  {
    title: "Star Wars: Episode IV - A New Hope",
    poster: "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_FMjpg_UX1000_.jpg",
    year: "1977",
    director: "George Lucas",
    genre: "Action",
  },
  {
    title: "Barbie",
    poster: "https://m.media-amazon.com/images/M/MV5BNjU3N2QxNzYtMjk1NC00MTc4LTk1NTQtMmUxNTljM2I0NDA5XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_FMjpg_UX1000_.jpg",
    year: "2023",
    director: "Greta Gerwig",
    genre: "Comedy",
  },
  {
    title: "The Wailing",
    poster: "https://m.media-amazon.com/images/M/MV5BODkwMTgxNjA2NF5BMl5BanBnXkFtZTgwMDc0OTcwOTE@._V1_.jpg",
    year: "2016",
    director: "Na Hong-jin",
    genre: "Horror",
  },
  {
    title: "Gadar 2",
    poster: "https://m.media-amazon.com/images/M/MV5BZGEzMDJjNGUtYTFhZi00MDgyLWIzMzYtMzcwMDQyZjcyNGY1XkEyXkFqcGdeQXVyNTcwNTM5ODI@._V1_FMjpg_UX1000_.jpg",
    year: "2023",
    director: "Anil Sharma",
    genre: "Action",
  },
]
